name: Trigger Portainer Build

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Portainer Stack Update
        env:
          PORTAINER_URL: 'https://5.161.118.67:9443'
          PORTAINER_USER: ${{ secrets.PORTAINER_USER }}
          PORTAINER_PASS: ${{ secrets.PORTAINER_PASS }}
          STACK_ID: ${{ secrets.PORTAINER_STACK_ID }}
          ENDPOINT_ID: ${{ secrets.PORTAINER_ENDPOINT_ID }}
        run: |
          # Debug output for secrets
          echo "Using Stack ID: $STACK_ID"
          echo "Using Endpoint ID: $ENDPOINT_ID"
          
          # Get JWT token with error handling
          echo "Attempting authentication..."
          response=$(curl -k -s -X POST "$PORTAINER_URL/api/auth" \
            -H "Content-Type: application/json" \
            -d "{\"Username\":\"$PORTAINER_USER\",\"Password\":\"$PORTAINER_PASS\"}")
          
          # Check if jq is available and parse JWT
          if ! command -v jq &> /dev/null; then
            echo "❌ jq command not found. Cannot parse JWT."
            exit 1
          fi
          jwt=$(echo "$response" | jq -r '.jwt')

          # Validate JWT - Moved this check *before* the success message
          if [ -z "$jwt" ] || [ "$jwt" = "null" ]; then
            echo "❌ Authentication failed. Response: $response"
            exit 1
          fi
          
          # If we reach here, authentication was successful
          echo "✅ Successfully obtained JWT token"

          # --- Clean potential hidden characters from IDs ---
          CLEAN_STACK_ID=$(echo "$STACK_ID" | tr -d '\r\n[:space:]')
          CLEAN_ENDPOINT_ID=$(echo "$ENDPOINT_ID" | tr -d '\r\n[:space:]')
          # -------------------------------------------------

          # Trigger stack update with validation using cleaned IDs
          if [ -z "$CLEAN_STACK_ID" ] || [ -z "$CLEAN_ENDPOINT_ID" ]; then
            echo "❌ Missing or invalid Stack ID or Endpoint ID after cleaning. Check GitHub Secrets."
            exit 1
          fi
          
          echo "Triggering redeploy of stack $CLEAN_STACK_ID..."
          # Print the cleaned URL
          CONSTRUCTED_URL="$PORTAINER_URL/api/stacks/$CLEAN_STACK_ID/git/redeploy?endpointId=$CLEAN_ENDPOINT_ID"
          echo "Constructed URL (Cleaned): $CONSTRUCTED_URL"
          
          # Use the cleaned variables in the curl command
          curl -k -v -X POST \  
            "$CONSTRUCTED_URL" \
            -H "Authorization: Bearer $jwt" \
            -H "Content-Type: application/json"
