name: Portainer Git Stack Redeploy

on:
  push:
    branches:
      - main

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy stack from Git in Portainer
        env:
          PORTAINER_URL: 'https://5.161.118.67:9443'
          PORTAINER_USER: ${{ secrets.PORTAINER_USER }}
          PORTAINER_PASS: ${{ secrets.PORTAINER_PASS }}
          STACK_ID: ${{ secrets.PORTAINER_STACK_ID }}
          ENDPOINT_ID: ${{ secrets.PORTAINER_ENDPOINT_ID }}
        run: |
          echo "🔐 Autenticando con Portainer..."

          JWT=$(curl -sk -X POST "$PORTAINER_URL/api/auth" \
            -H "Content-Type: application/json" \
            -d "{\"Username\":\"$PORTAINER_USER\",\"Password\":\"$PORTAINER_PASS\"}" | jq -r '.jwt')

          if [ -z "$JWT" ] || [ "$JWT" = "null" ]; then
            echo "❌ Autenticación fallida."
            exit 1
          fi

          echo "✅ Autenticación exitosa."

          echo "🚀 Disparando redeploy de stack conectado a Git..."

          REDEPLOY_URL="$PORTAINER_URL/api/stacks/$STACK_ID/git/redeploy?endpointId=$ENDPOINT_ID"

          HTTP_CODE=$(curl -sk -o /dev/null -w "%{http_code}" -X POST "$REDEPLOY_URL" \
            -H "Authorization: Bearer $JWT" \
            -H "Content-Type: application/json")

          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Stack redeploy exitoso 🚀"
          else
            echo "❌ Redeploy fallido. Código HTTP: $HTTP_CODE"
            exit 1
          fi
