name: Trigger Portainer Build

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Portainer Stack Update
        env:
          PORTAINER_URL: 'https://5.161.118.67:9443'
          PORTAINER_USER: ${{ secrets.PORTAINER_USER }}
          PORTAINER_PASS: ${{ secrets.PORTAINER_PASS }}
          STACK_ID: ${{ secrets.PORTAINER_STACK_ID }}
          ENDPOINT_ID: ${{ secrets.PORTAINER_ENDPOINT_ID }}
        run: |
          # Get JWT token with verbose output
          echo "Attempting authentication with Portainer..."
          response=$(curl -k -v -s -X POST "$PORTAINER_URL/api/auth" \
            -H "Content-Type: application/json" \
            -d "{\"Username\":\"$PORTAINER_USER\",\"Password\":\"$PORTAINER_PASS\"}")
          
          echo "Raw response: $response"
          JWT=$(echo $response | jq -r '.jwt')
          
          if [ -z "$JWT" ]; then
            echo "❌ Failed to get JWT token"
            exit 1
          fi
          
          echo "✅ Successfully obtained JWT token"
          
          # Trigger stack update
          echo "Triggering stack update..."
          curl -k -v -X POST \
            "$PORTAINER_URL/api/stacks/$STACK_ID/git/redeploy?endpointId=$ENDPOINT_ID" \
            -H "Authorization: Bearer $JWT" \
            -H "Content-Type: application/json"